INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'first Description', 'first Title', 1);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'second Description', 'second Title', 2);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'third Description', 'third Title', 1);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'Random Description', 'Count Striker', 3);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'Random Description', 'Video Game', 4);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'Random Description', 'Talk About ...', 4);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'Random Description', 'Party!', 4);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'first Description', 'Title', 1);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'second Description', 'Fourth Title', 2);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'third Description', 'Fifth Title', 1);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'Random Description', 'Size Striker', 3);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'Random Description', 'Audio Game', 4);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'Random Description', 'What up?', 4);
INSERT INTO channels (createdTS, description, title, ownerId) VALUES (now(), 'Random Description', 'Second Party!', 4);
