INSERT INTO FAVORITECHANNELS (USERID, CHANNELID) VALUES (1,2);
INSERT INTO FAVORITECHANNELS (USERID, CHANNELID) VALUES (1,4);
INSERT INTO FAVORITECHANNELS (USERID, CHANNELID) VALUES (1,6);
INSERT INTO FAVORITECHANNELS (USERID, CHANNELID) VALUES (2,5);
INSERT INTO FAVORITECHANNELS (USERID, CHANNELID) VALUES (3,1);
INSERT INTO FAVORITECHANNELS (USERID, CHANNELID) VALUES (4,3);